### ISSUE TITLE
עדכון מסך הוספת קבוצה

### ISSUE THREAD

**Issue by orenpinto** [sapirshp/MeetApp#31]
עדכון צבעים ולחצנים כך שיתאים יותר לאפליקציה
הסרת לחצן הוספת לוגו לקבוצה
הקפאת כפתור הוספת קבוצה כשמנסים להכניס שם ריק
לא לסגור את הפופ אפ כשמנסים להכניס שם שכבר קיים + הצגת הtoast בגובה יותר רלוונטי במסך מאשר התחתית (כפי שעכשיו)

**Comment by Chen-Ben-yashar** [comment]
done
